package edu.eci.arsw.collabboard.domain.model;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Aggregate root: a simple plane made of visual elements.
 *
 * Minimum domain invariants:
 * - {@code id} must be a non-blank identifier (generated by the server).
 * - {@code name} must be non-blank.
 * - {@code elements} is never {@code null}, has no {@code null} items and is stored as an immutable copy.
 * - element ids are unique within the board.
 * - Lab 05: every CONNECTOR joins two existing elements of this same board.
 *
 * No HTTP, persistence or framework concern belongs in this class.
 */
public record Board(String id, String name, List<BoardElement> elements) {
    public Board {
        if (id == null || id.isBlank()) {
            throw new IllegalArgumentException("Board id is required");
        }
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Board name is required");
        }
        if (elements != null && elements.stream().anyMatch(Objects::isNull)) {
            throw new IllegalArgumentException("Board elements cannot contain null");
        }
        elements = elements == null ? List.of() : List.copyOf(elements);
        Map<String, BoardElement> byId = new HashMap<>();
        for (BoardElement element : elements) {
            if (byId.putIfAbsent(element.id(), element) != null) {
                throw new IllegalArgumentException("Duplicate element id: " + element.id());
            }
        }
        for (BoardElement element : elements) {
            if (element.type() == ElementType.CONNECTOR) {
                requireExistingEndpoint(byId, element, element.sourceId());
                requireExistingEndpoint(byId, element, element.targetId());
            }
        }
    }

    private static void requireExistingEndpoint(Map<String, BoardElement> byId, BoardElement connector, String endpointId) {
        if (!byId.containsKey(endpointId)) {
            throw new IllegalArgumentException(
                    "Connector " + connector.id() + " references a missing element: " + endpointId);
        }
    }
}