package edu.eci.arsw.collabboard.domain.model;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Aggregate root: a simple plane made of visual elements.
 *
 * Minimum domain invariants (Lab 04):
 * - {@code id} must be a non-blank identifier (generated by the server).
 * - {@code name} must be non-blank.
 * - {@code elements} is never {@code null} and is stored as an immutable copy.
 * - element ids are unique within the board.
 *
 * No HTTP, persistence or framework concern belongs in this class.
 */

public record Board(String id, String name, List<BoardElement> elements) {
    public Board {
        if (id == null || id.isBlank()) {
            throw new IllegalArgumentException("Board id is required");
        }
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Board name is required");
        }
        elements = elements == null ? List.of() : List.copyOf(elements);
        Set<String> seen = new HashSet<>();
        for (BoardElement element : elements) {
            if (!seen.add(element.id())) {
                throw new IllegalArgumentException("Duplicate element id: " + element.id());
            }
        }
    }
}
